name: CI Pipeline

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  frontend:
    name: Angular Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration=production

  backend:
    name: Spring Boot Build & Integration Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven Wrapper
        run: |
          chmod +x ../mvnw
          ../mvnw clean verify

      - name: Build Firebase Emulator image
        run: |
          docker build -t custom-firebase-emulator:latest src/test/resources/docker

      - name: Start Firebase Emulator container
        run: |
          docker run -d --name firebase-emulator -p 9080:9080 custom-firebase-emulator:latest

      - name: Wait for Firebase Emulator to be ready
        run: |
          for i in {1..30}; do
            curl -f http://localhost:9080 && break
            echo "Waiting for emulator to start..."
            sleep 5
          done

      - name: Build and test Spring Boot application
        run: |
          ../mvnw clean verify -Dspring.profiles.active=test

      - name: Stop Firebase Emulator container
        if: always()
        run: |
          docker stop firebase-emulator
          docker rm firebase-emulator
